### ISSUE TITLE
#info Template

### ISSUE THREAD

**Issue by redgitid** [ratabb/Hishoot2i#3]
Hi, Where can I download templates of other devices to use in hishoot?

**Comment by ratabb** [comment]
@RedMoonOTInetwork Templates created by community, you can search in
 - [Facebook](https://www.facebook.com/groups/hishoot.template)
 - [Google+](https://plus.google.com/communities/115724885071998017281)

Or, you can create your own with an example from [here](https://github.com/hishoot2i/TemplateHishoot)

**Comment by redgitid** [comment]
Thanks

**Comment by redgitid** [comment]
Sorry, I did not understand how to create a template, there is a guide?

**Comment by ratabb** [comment]
- github.com/hishoot2i/TemplateHishoot/blob/master/templatev2/README.md

- youtube.com/watch?v=cSL9uixrtak
- youtube.com/watch?v=DWKjafddg8c

- lmddgtfy.net/?q=hishoot%20template

**Comment by redgitid** [comment]
Thanks
