### ISSUE TITLE
Absolutely love this app any plans for video templates

### ISSUE THREAD

**Issue by AbhimanyuAryan** [ratabb/Hishoot2i#6]
I use this app a lot. Are there any plans for premium version that can also support video play? 
![HiShoot_20200713_182931](https://user-images.githubusercontent.com/8083613/87383656-77ee1480-c5b7-11ea-935b-53ed90e5dc9a.png)

Also would love to contribute to project if you want

**Comment by ratabb** [comment]
Hi, thank you for using this app.

No, I'm not have plan for `premium` version or playing video on.
