### ISSUE TITLE
Wish template-apks can be imported by template-manager of Hishoot2i APP

### ISSUE THREAD

**Issue by gang4399** [ratabb/Hishoot2i#9]
Wish template-apks can be imported by template-manager of Hishoot2i APP, but do not need installed by
the Android system.
Import , export , editor are total supported is perfect .

**Comment by ratabb** [comment]
Hi @gang4399, thank you for using Hishoot2i.

Yup, template Hishoot2i should be not depend on framework (Android System), but for template-apks I think, I can not do that.

My plan is drop support template-apks, only template-htz for HiShoot2i App. I must provide `converter` template-apks to template-htz fist. Maybe next release Hishoot2i is last version for support template-apks and add `converter`.

**Comment by gang4399** [comment]
> Hi @gang4399, thank you for using Hishoot2i.
> 
> Yup, template Hishoot2i should be not depend on framework (Android System), but for template-apks I think, I can not do that.
> 
> My plan is drop support template-apks, only template-htz for HiShoot2i App. I must provide `converter` template-apks to template-htz fist. Maybe next release Hishoot2i is last version for support template-apks and add `converter`.

Thanks to the good job.Best wish to you&yours update.
There are some mod app base on Hi2 as "带壳截图Pro" or"Hishoot2i material" also going well on those demands.

**Comment by ratabb** [comment]
>  There are some mod app base on Hi2 as "带壳截图Pro" or"Hishoot2i material" also going well on those demands.

idk bout that, thanks.

Hishoot2i also mod from [Hishoot](https://github.com/jmkl/Hishoot) and get influence from [Device Frame Generator](https://github.com/f2prateek/device-frame-generator), and many other Open Source like this. But, I'm not give proper credit to them. that's my sin ✌️
